"""Add due_date to assigned_courses

Revision ID: 160959f9037a
Revises: 374ea9c41a8a
Create Date: 2025-07-08 00:37:19.324406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160959f9037a'
down_revision: Union[str, Sequence[str], None] = '374ea9c41a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_courses', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assigned_courses', 'due_date')
    # ### end Alembic commands ###
